### ISSUE TITLE
Auth + hosting

### ISSUE THREAD

**Issue by 8enmann** [JasonBenn/flock#1]
AuthZero is probably the easiest option
https://auth0.com/docs/quickstart/backend/python/01-authorization

For hosting I can throw it on my digitalocean dokku or we could use appengine

**Comment by JasonBenn** [comment]
Would think that [Django's built-in user](https://docs.djangoproject.com/en/2.2/topics/auth/) auth would be easier and require less code - you sure about AuthZero?

Happy to continue hosting on ml-box (192.168.86.86 internally), we'll just need to direct incoming traffic to the router to it. There's already an nginx setup on the machine, it'll just need to forward traffic from 80 and 443 to the web server on 8000.

**Comment by 8enmann** [comment]
I want to support OAuth (hate passwords). Have heard really good things about AuthZero. I've tried hosting things on mlbox before and it was really slow. cloud hosted means it'll never go down because someone had to reboot the machine. If you prefer it local for some reason I'm open to it though.

**Comment by JasonBenn** [comment]
Neat - AuthZero SGTM
And happy to cloud host too, just thought I'd offer the option as it'd be easier.

**Comment by 8enmann** [comment]
Fixed by 87a7cbe82f4bc250d69739c64c809cbc7ddb1feb
